#
# arkafe.com
#
# www to non-www
server {

    listen              443 ssl;
    server_name         www.arkafe.com;

    ssl_certificate     /etc/letsencrypt/live/arkafe.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/arkafe.com/privkey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    return 301 $scheme://arkafe.com$request_uri;
}

server {

    listen              443 ssl;
    server_name         arkafe.com;

    ssl_certificate     /etc/letsencrypt/live/arkafe.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/arkafe.com/privkey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    root /var/www/me/arkafe/website/public;

    index index.html index.htm index.php;
    
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
    }

    error_page 404 /index.php;

    location ~ /\. {
        deny all;
    }
    
}

server {

    listen              443 ssl;
    server_name         concert.arkafe.com;

    ssl_certificate     /etc/letsencrypt/live/arkafe.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/arkafe.com/privkey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    root /var/www/me/arkafe/concert5/appengine/w3root;

    index index.cgi index.php;
    
    location /rolodex/ {
        try_files $uri /rolodex/index.php$is_args$args;
    }
    
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.(php|cgi)$ {
    
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
	

        # include snippets/fastcgi-php.conf;
        
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        include fastcgi_params;

    }

    error_page 404 /index.php;

    location ~ /\. {
        deny all;
    }
    
}


server {

    listen              443 ssl;
    server_name         appengine.arkafe.com;

    ssl_certificate     /etc/letsencrypt/live/arkafe.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/arkafe.com/privkey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    root /var/www/appengine/w3root;

    index index.php;
    
    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.(php|cgi)$ {
    
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
	

        # include snippets/fastcgi-php.conf;
        
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        include fastcgi_params;

    }

    error_page 404 /index.php;

    location ~ /\. {
        deny all;
    }
    
}


